config/routes.rb
Rails.application.routes.draw do
  #setting index page
  root  'contacts#index'

  resources :contacts

  get 'pages/about'
  get 'pages/home'
  get 'pages/contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    
    def contact_params
        params.require(:contact).permit(:name, :number , :age)
    end

    def index
        @contacts = Contact.all
    end

    def show
        @contact = Contact.find(params[:id])

    end
    def new
        @contact = Contact.new
    end
    def create
        @contact = Contact.new(contact_params)
        
        if @contact.save
            redirect_to contacts_path, :notice => "your contact was saved" 
        else
            render "new"
        end


    end

    def edit
        @contact = Contact.find(params[:id])


    end

    def update

        @contact = Contact.find(params[:id])
        
        if @contact.update_attributes(contact_params)
            redirect_to contacts_path, :notice => "changes have been saved"
        else
            render "edit"
        end

    end

    def destroy
        @contact = Contact.find(params[:id])
        @contact.destroy
        redirect_to contacts_path , :notice => "contact has been deleted"


    end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def home
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/edit.html.erb
<h1>edit contact</h1>


<%= form_for @contact do |form|%>

    <p>
         <%= form.label :name %><br />
         <%= form.text_field  :name %>
    </p>
    <p>
         <%= form.label :number %><br />
         <%= form.text_field  :number %>
    </p>

    <p>
        <%= form.label :age %><br />
        <%= form.number_field  :age %>
    </p>

    <p>
        <%= form.submit "save changes" %>
    </p>


<% end %>

app/views/contacts/index.html.erb
<% @contacts.each do |contact| %>
    <h2>name: <%= link_to contact.name, contact %></h2>
    <p>number : <%= contact.number %></p>
    
    <hr />
<% end %>



<p><%= link_to "add new contact", new_contact_path %></p>

app/views/contacts/new.html.erb
<h1>add a new contact</h1>


<%= form_for @contact do |form| %>
    <p>
         <%= form.label :name %><br />
         <%= form.text_field  :name %>
    </p>
    <p>
         <%= form.label :number %><br />
         <%= form.text_field  :number %>
    </p>

    <p>
        <%= form.label :age %><br />
        <%= form.number_field  :age %>
    </p>

    <p>
        <%= form.submit "add new contact" %>
    </p>


<%end%>

app/views/contacts/show.html.erb
<h1>name : <%= @contact.name %></h1>
<p>number : <%= @contact.number %></p>
<p>age : <%= @contact.age %></p>
<p>created at : <%= @contact.created_at %></p>
<p>
    <%= link_to "edit contact" , edit_contact_path(@contact) %><br />
    <%= link_to "delete contact" , @contact, :method => :delete %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', :confirm => "are you sure you want to delete?", media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% flash.each do |key , value| %>
      <p><%= value %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>hello world!!!#</h1>
<%= 'this is embede ruby' %>